apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-sre-app
  labels:
    app: desafio-sre-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desafio-sre-app
  template:
    metadata:
      labels:
        app: desafio-sre-app
    spec:
      containers:
      - name: desafio-sre-app
        image: gersontpc/desafio-sre-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_SDK_DISABLED
          value: "false"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://tempo.monitoring.svc.cluster.local:4318/v1/traces"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
          value: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: http://prometheus-server.monitoring.svc.cluster.local"
        #- name: OTEL_METRICS_EXPORTER
        #  value: "prometheus"
        #- name: OTEL_METRICS_EXPORTER_PORT
        #  value: "9464"
        #- name: OTEL_METRICS_EXPORTER_HOST
        #  value: "http://prometheus-server.monitoring.svc.cluster.local"
        - name: OTEL_SERVICE_NAME
          value: "desafio-sre-app"
        - name: OTEL_INSTRUMENTATION_LIBRARY_NAMES
          value: "java.util.logging"