apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-sre-app
  labels:
    app: desafio-sre-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desafio-sre-app
  template:
    metadata:
      labels:
        app: desafio-sre-app
    spec:
      containers:
      - name: desafio-sre-app
        image: gersontpc/desafio-sre-app:latest
        ports:
        - containerPort: 80